import { 
  Footprints, 
  ShieldCheck, 
  Calendar, 
  Coffee, 
  Zap, 
  Wifi, 
  Sun, 
  ShoppingBag, 
  Mountain, 
  Home, 
  Globe, 
  Plane, 
  Gem, 
  Timer, 
  Leaf, 
  Star, 
  Smile, 
  Users, 
  Crown, 
  Rocket
} from 'lucide-react';

export const MILESTONES_CONFIG = [
  { icon: Footprints, color: "from-slate-400 to-slate-600" },
  { icon: ShieldCheck, color: "from-blue-400 to-blue-600" },
  { icon: Calendar, color: "from-indigo-400 to-indigo-600" },
  { icon: Coffee, color: "from-amber-600 to-amber-800" },
  { icon: Zap, color: "from-yellow-400 to-yellow-600" },
  { icon: Wifi, color: "from-sky-400 to-sky-600" },
  { icon: Sun, color: "from-orange-300 to-orange-500" },
  { icon: ShoppingBag, color: "from-lime-500 to-lime-700" },
  { icon: Mountain, color: "from-emerald-500 to-emerald-700" },
  { icon: Home, color: "from-rose-400 to-rose-600" },
  { icon: Globe, color: "from-cyan-500 to-cyan-700" },
  { icon: Plane, color: "from-violet-400 to-violet-600" },
  { icon: Gem, color: "from-pink-400 to-pink-600" },
  { icon: Timer, color: "from-teal-500 to-teal-700" },
  { icon: Leaf, color: "from-green-400 to-green-600" },
  { icon: Star, color: "from-yellow-300 to-yellow-500" },
  { icon: Smile, color: "from-orange-400 to-orange-600" },
  { icon: Users, color: "from-purple-500 to-purple-700" },
  { icon: Crown, color: "from-amber-400 to-amber-600" },
  { icon: Rocket, color: "from-red-500 to-red-700" }
];
